# Site settings
title: Yifan Cheng
header-img: img/yifan/main_bg1.jpeg
email: yifanc6@uw.edu
description: "Yifan Cheng"
# baseurl: "/"
url: "http://yifancheng.com/"
twitter_username: YifanCheng4
github_username:  yifancheng
facebook_username:  yifanc6

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
